
name: Node.js Package

on:
  push:
    branches:
      - main
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: node --version
      - run: npm --version
      - run: npm install
  deploy:
    runs-on: ubuntu-latest
    needs: build-node
    if: success()  && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.FiddlerMapper_ServiceId }}
          api_key: ${{ secrets.FiddlerMapper_API_KEY }}
    
